### ISSUE TITLE
Decide on INCOSE presentation, tutorial, or nothing

### ISSUE THREAD

**Issue by rbedman** [mlte-team/mlte#501] opened 2024-10-28 20:37 UTC

**Comment by rbedman** [comment] 2024-10-28 20:41
Past tutorials: Half day or Full day

**Comment by krmaffey** [comment] 2024-10-28 20:47
Submissions for [presentations](https://www.incose.org/docs/default-source/events-documents/is2025/promotion/iscall-for-submissions.pdf?sfvrsn=e9a257c7_2) includes an extended abstract of no more than 1,000 words and include:
- An overview of the topic – define the systems engineering (SE) challenge of interest and its context
- Clearly identify specific related industries – explain why the problem is important and is worth studying under a SE approach
- Provide what the audience will take away from the presentation – outline methods and describe expected results
- Provide background

**Comment by rbedman** [comment] 2024-11-04 19:51
Decided on a presentation - 1000 word abstract. We don't have enough content for a tutorial, don't want to commit to a full paper. 

@krmaffey will outline, we will review on 11/11

**Comment by krmaffey** [comment] 2024-11-18 15:24
@rbedman and @krmaffey are writing the abstract, we decided to submit for a presentation. Closing this issue, the submission is addressed by issue #537

**Closed by krmaffey** 2024-11-18 15:24 UTC
