### ISSUE TITLE
Add NegotiationCard entity

### ISSUE THREAD

**Issue by sebastian-echeverria** [mlte-team/mlte#142] opened 2023-05-11 17:32 UTC
We want to start using and storing the NegotiationCard entity with MLTE. Add it as a first-level entity, that can be handled, stored and retrieved similarly to Spec.

Details of the Negotiation Card can be found here: https://github.com/mlte-team/mlte-framework/blob/master/framework/resources/process/negotiation_card.md

**Comment by turingcompl33t** [comment] 2023-06-07 14:54
Closing as a duplicate of #151.

**Closed by turingcompl33t** 2023-06-07 14:54 UTC
